HPARAMS = {
    'cifar10_lr_06_batch_128' : {
        'batch' : 128,
        'workers' : 4,
        'hparams' : {
            'total_steps' : 160000,
            'eval_steps' : 1000,
            'warmup_steps' : 0,
            'optim' : 'sgd',
            'weight_decay' : 5e-4,
            'momentum' : 0.9,
            'lr' : 0.3,
            'decay' : 'cosine',
        },
    },
    'cifar10_lr_006_batch_128' : {
        'batch' : 128,
        'workers' : 4,
        'hparams' : {
            'total_steps' : 160000,
            'eval_steps' : 1000,
            'warmup_steps' : 0,
            'optim' : 'sgd',
            'weight_decay' : 5e-4,
            'momentum' : 0.9,
            'lr' : 0.06,
            'decay' : 'cosine',
        },
    },
    'cifar10_lr_0006_batch_128' : {
        'batch' : 128,
        'workers' : 4,
        'hparams' : {
            'total_steps' : 160000,
            'eval_steps' : 1000,
            'warmup_steps' : 0,
            'optim' : 'sgd',
            'weight_decay' : 5e-4,
            'momentum' : 0.9,
            'lr' : 0.006,
            'decay' : 'cosine',
        },
    },
    'cifar10_lr_00006_batch_128' : {
        'batch' : 128,
        'workers' : 4,
        'hparams' : {
            'total_steps' : 160000,
            'eval_steps' : 1000,
            'warmup_steps' : 0,
            'optim' : 'sgd',
            'weight_decay' : 5e-4,
            'momentum' : 0.9,
            'lr' : 0.0006,
            'decay' : 'cosine',
        },
    },
    'inat_lr_001_batch_60_wd_0001' : {
        'batch' : 60,
        'workers' : 4,
        'hparams' : {
            'total_steps' : 250000,
            'eval_steps' : 1000,
            'warmup_steps' : 0,
            'optim' : 'sgd',
            'weight_decay' : 0.001,
            'momentum' : 0.9,
            'lr' : 0.01,
            'decay' : 'cosine',
        },
    },
    'inat_lr_0001_batch_60_wd_0001' : {
        'batch' : 60,
        'workers' : 4,
        'hparams' : {
            'total_steps' : 250000,
            'eval_steps' : 1000,
            'warmup_steps' : 0,
            'optim' : 'sgd',
            'weight_decay' : 0.001,
            'momentum' : 0.9,
            'lr' : 0.001,
            'decay' : 'cosine',
        },
    },
    'inat_lr_00001_batch_60_wd_0001' : {
        'batch': 60,
        'workers': 4,
        'hparams': {
            'total_steps': 250000,
            'eval_steps': 1000,
            'warmup_steps': 0,
            'optim': 'sgd',
            'weight_decay': 0.001,
            'momentum': 0.9,
            'lr': 0.0001,
            'decay': 'cosine',
        },
    },
}

HPARAM_CANDIDATES = {
    'cifar' : [
        'cifar10_lr_00006_batch_128',
        'cifar10_lr_0006_batch_128',
        'cifar10_lr_006_batch_128',
        'cifar10_lr_06_batch_128',
    ],
    'inat' : [
        'inat_lr_001_batch_60_wd_0001',
        'inat_lr_0001_batch_60_wd_0001',
        'inat_lr_00001_batch_60_wd_0001',
    ],
}
