sh train_partial_feedback.sh partial_feedback
sh train_partial_feedback.sh partial_feedback_weight_history_0

CUDA_VISIBLE_DEVICES=1 sh train_partial_feedback.sh partial_feedback_weight_history_2
CUDA_VISIBLE_DEVICES=1 sh train_partial_feedback.sh partial_feedback_weight_history_0.5

CUDA_VISIBLE_DEVICES=2 sh train_partial_feedback.sh log_in_partial_feedback
CUDA_VISIBLE_DEVICES=2 sh train_partial_feedback.sh log_in_partial_feedback_weight_history_0

CUDA_VISIBLE_DEVICES=3 sh train_partial_feedback.sh log_in_partial_feedback_weight_history_2
CUDA_VISIBLE_DEVICES=3 sh train_partial_feedback.sh log_in_partial_feedback_weight_history_0.5

python generate_table.py --partial_feedback_mode partial_feedback
python generate_table.py --partial_feedback_mode partial_feedback_weight_history_0
python generate_table.py --partial_feedback_mode partial_feedback_weight_history_2
python generate_table.py --partial_feedback_mode partial_feedback_weight_history_0.5
python generate_table.py --partial_feedback_mode log_in_partial_feedback
python generate_table.py --partial_feedback_mode log_in_partial_feedback_weight_history_0
python generate_table.py --partial_feedback_mode log_in_partial_feedback_weight_history_2
python generate_table.py --partial_feedback_mode log_in_partial_feedback_weight_history_0.5

sh debug_partial_feedback.sh debug_partial_feedback_weight_history_0
sh debug_partial_feedback.sh debug_log_in_partial_feedback_weight_history_0